[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim' # Type gcc when toggle comment out

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'cocopon/vaffle.vim'
# [[plugins]]
# repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

####################
# Statusbar and tabline
####################
[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


####################
# Colorscheme
####################
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# [[plugins]]
# repo = 'altercation/vim-colors-solarized'

# [[plugins]]
# repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'sjl/badwolf'

# [[plugins]]
# repo = 'notpratheek/vim-luna'

# [[plugins]]
# repo = 'joshdick/onedark.vim'

# [[plugins]]
# repo = 'sickill/vim-monokai'

# [[plugins]]
# repo = 'junegunn/seoul256.vim'

# [[plugins]]
# repo = 'dracula/vim'

# [[plugins]]
# repo = 'jpo/vim-railscasts-theme'


####################
# Markdown
####################
# [[plugins]]
# repo = 'plasticboy/vim-markdown'

# [[plugins]]
# repo = 'kannokanno/previm'

# [[plugins]]
# repo = 'tyru/open-browser.vim'


####################
# Golang
####################
# [[plugins]]
# repo = 'fatih/vim-go'


####################
# PHP
####################
# [[plugins]]
# repo = 'nishigori/vim-php-dictionary'
# on_ft = 'php'

# [[plugins]]
# repo = 'joonty/vdebug'


####################
# Python
####################
# [[plugins]]
# repo = 'davidhalter/jedi-vim'

# [[plugins]]
# repo = 'Vimjas/vim-python-pep8-indent'
# on_ft = 'python'
