brew "mas"
brew "zplug"
brew "go"
brew "ghq"
brew "nodebrew"
brew "tig"
brew "htop"

# cask "1password"
# cask "firefox"
# cask "google-chrome"
# cask "iterm2"
# cask "mysqlworkbench"
# cask "visual-studio-code"

mas "Slack", id: 803453959
