set guioptions-=m
set guioptions-=T

set lines=48
set columns=164

" Disable beep
set visualbell t_vb=


if has("unix")
    set guifont=Monospace\ 11
endif

" Key Mappings
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l  
