""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" Author: NakanishiTetsuhiro
" Github: https://github.com/NakanishiTetsuhiro/dotfiles
"
" Please execute the following command manually at first time startup
" git clone https://github.com/Shougo/dein.vim.git ~/.cache/dein/repos/Shougo/dein.vim
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

if &compatible
  set nocompatible
endif

let s:dein_dir = expand('~/.cache/dein') " Plugins install location

let s:dein_repo_dir = s:dein_dir . '/repos/Shougo/dein.vim' " dein.vim location
 
if has('unix') || has('mac') " Set runtimepath
    execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
elseif has('win32') || has ('win64')
    execute 'set runtimepath^=$HOME\.cache\dein\repos\Shougo\dein.vim'
endif


" Dein setting start
call dein#begin(s:dein_dir)

call dein#add('Shougo/unite.vim')
call dein#add('ujihisa/unite-colorscheme')

call dein#add('Shougo/vimfiler')
call dein#add('Shougo/neocomplete.vim')
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/vimshell.vim')
call dein#add('Shougo/neosnippet-snippets')

if has('unix') || has('mac')
    call dein#add('Shougo/vimproc.vim', {'build' : 'make'})
endif

call dein#add('tpope/vim-fugitive')
call dein#add('Konfekt/FastFold')
call dein#add('mattn/emmet-vim')
call dein#add('majutsushi/tagbar')
call dein#add('tomtom/tcomment_vim') " Type gcc when toggle comment out
call dein#add('christoomey/vim-tmux-navigator')
call dein#add('itmammoth/doorboy.vim')
call dein#add('tpope/vim-surround')
call dein#add('junegunn/vim-easy-align')
call dein#add('thinca/vim-ref')

" Dictionaries
call dein#add('nishigori/vim-php-dictionary', {'on_ft': 'php'})

" Colorscheme
call dein#add('altercation/vim-colors-solarized')
call dein#add('w0ng/vim-hybrid')
call dein#add('tomasr/molokai')
call dein#add('sjl/badwolf')
call dein#add('notpratheek/vim-luna')
call dein#add('joshdick/onedark.vim')

" Statusbar and tabline
call dein#add('bling/vim-airline')
call dein#add('vim-airline/vim-airline-themes')

" Markdown
call dein#add('plasticboy/vim-markdown')
call dein#add('kannokanno/previm')
call dein#add('tyru/open-browser.vim')

" ctags assist. Type :TagsGenerate when update ctags
call dein#add('szw/vim-tags')

" Golang
call dein#add('fatih/vim-go')

" Python
call dein#add('davidhalter/jedi-vim')

call dein#end()
call dein#save_state()

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

filetype plugin indent on


" Other Settings
source $HOME/dotfiles/vim-dotfiles/basic.vim
source $HOME/dotfiles/vim-dotfiles/key-mappings.vim
source $HOME/dotfiles/vim-dotfiles/plugin_settings.vim
source $HOME/dotfiles/vim-dotfiles/other_settings.vim

