- hosts: localhost
  connection: local
  tasks:
      - name: Copy config.fish
        synchronize: src=~/dotfiles/src/fish/config.fish dest=~/.config/fish/config.fish

      - name: Copy ftplugin directory
        synchronize: src=~/dotfiles/src/vim/ftplugin dest=~/.vim/ftplugin

      - name: Create symlinks1
        file:
          src: ~/dotfiles/src/{{ item }}/.{{ item }}rc
          dest: ~/.{{ item }}rc
          state: link
          force: no
        with_items:
          - bash
          - zsh
          - tig

      - name: Create tmux symlink
        file:
          src: ~/dotfiles/src/tmux/.tmux.conf
          dest: ~/.tmux.conf
          state: link
          force: no

      - name: Create ctags symlink
        file:
          src: ~/dotfiles/src/ctags/.ctags
          dest: ~/.ctags
          state: link
          force: no

      - name: Create vimrc symlink
        file:
          src: ~/dotfiles/src/vim/.vimrc
          dest: ~/.vimrc
          state: link
          force: yes
